server {
    listen 80;
    listen [::]:80;
    server_name danielscience.com www.danielscience.com;
    root /var/www/danielscience.com;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
}
